/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectodeportivo;

/**
 *
 * @author HP
 */
public class Consulta extends javax.swing.JFrame {

    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListaParticipante = new javax.swing.JLabel();
        ListaEvento = new javax.swing.JLabel();
        ListaResultado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ConsultarParticipantes = new javax.swing.JButton();
        ConsultaEvento = new javax.swing.JButton();
        ConsultaResultado = new javax.swing.JButton();
        ListaParticipante1 = new javax.swing.JLabel();
        ListaEvento1 = new javax.swing.JLabel();
        ListaResultado1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        ListaParticipante.setText(" lista de  Participantes");

        ListaEvento.setText(" Lista de Eventos");

        ListaResultado.setText("Resultados ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ConsultarParticipantes.setText("Consultar Participantes");
        ConsultarParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarParticipantesActionPerformed(evt);
            }
        });

        ConsultaEvento.setText("Consultar Evento");
        ConsultaEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaEventoActionPerformed(evt);
            }
        });

        ConsultaResultado.setText("Consultar Resultados ");
        ConsultaResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaResultadoActionPerformed(evt);
            }
        });

        ListaParticipante1.setText(" lista de  Participantes");

        ListaEvento1.setText(" Lista de Eventos");

        ListaResultado1.setText("Resultados ");

        jLabel1.setText("CONSULTAS ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ConsultarParticipantes)
                .addGap(18, 18, 18)
                .addComponent(ConsultaEvento)
                .addGap(18, 18, 18)
                .addComponent(ConsultaResultado)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(ListaParticipante1)
                .addGap(46, 46, 46)
                .addComponent(ListaEvento1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ListaResultado1)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(200, 200, 200))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListaParticipante1)
                    .addComponent(ListaEvento1)
                    .addComponent(ListaResultado1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultarParticipantes)
                    .addComponent(ConsultaEvento)
                    .addComponent(ConsultaResultado))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarParticipantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarParticipantesActionPerformed

    private void ConsultaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaEventoActionPerformed

    private void ConsultaResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultaEvento;
    private javax.swing.JButton ConsultaResultado;
    private javax.swing.JButton ConsultarParticipantes;
    private javax.swing.JLabel ListaEvento;
    private javax.swing.JLabel ListaEvento1;
    private javax.swing.JLabel ListaParticipante;
    private javax.swing.JLabel ListaParticipante1;
    private javax.swing.JLabel ListaResultado;
    private javax.swing.JLabel ListaResultado1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
